name: Function App Test Template

on:
  workflow_call:
    inputs:
      logic_app_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Logic App."

jobs:
  deployment:
    name: Function App Test
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v3

      # Package Logic App
      - name: Package Logic App
        id: logic_app_package
        working-directory: ${{ inputs.logic_app_directory }}
        run: |
          echo "Create outputs directory..."
          mkdir -p ./../../output

          echo "zip logic app content"
          zip -r ./../../output/logic.zip .

      # Tree
      - name: Tree
        id: tree
        run: |
          tree

      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: logic
      #     path: "./output"
      #     retention-days: 1
