name: Logic App Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      logic_app_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Logic App."
      logic_app_name:
        required: true
        type: string
        description: "Specifies the name of the Azure Logic App."
      tenant_id:
        required: true
        type: string
        description: "Specifies the tenant id of the deployment."
      subscription_id:
        required: true
        type: string
        description: "Specifies the subscription id of the deployment."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."
      CLIENT_SECRET:
        required: true
        description: "Specifies the client secret."

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Logic App Deploy
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v4

      # Azure login
      - name: Azure login
        id: azure_login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      # Package Logic App
      - name: Package Logic App
        id: logic_app_package
        working-directory: ${{ inputs.logic_app_directory }}
        run: |
          echo "Create outputs directory..."
          mkdir -p ./../../output

          echo "zip logic app content"
          zip -r ./../../output/logic.zip .

      # Deploy Logic App
      - name: Deploy Logic App
        id: logic_deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.logic_app_name }}
          package: "./output/logic.zip"
