name: Logic App Deployment
on:
  push:
    branches:
      - main
    paths:
      - "code/logicApp001/**"

  pull_request:
    branches:
      - main
    paths:
      - "code/logicApp001/**"

jobs:
  logic_app_test:
    uses: ./.github/workflows/_logicAppTestTemplate.yml
    name: "Logic App Test"
    with:
      logic_app_directory: "code/logicApp001"

  logic_app_deploy:
    uses: ./.github/workflows/_logicAppDeployTemplate.yml
    name: "Logic App Deploy"
    needs: [logic_app_test]
    if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      logic_app_directory: "code/logicApp001"
      logic_app_name: "mylogic-dev-la001"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
