name: Function App Deployment
on:
  push:
    branches:
      - main
    paths:
      - "code/logicApp001/**"

  pull_request:
    branches:
      - main
    paths:
      - "code/logicApp001/**"

jobs:
  function_test:
    uses: ./.github/workflows/_logicAppTestTemplate.yml
    name: "Function App Test"
    with:
      logic_app_directory: "./code/logicApp001"

  function_deploy:
    uses: ./.github/workflows/_logicAppDeployTemplate.yml
    name: "Function App Deploy"
    needs: [function_test]
    # if: github.event_name == 'push' || github.event_name == 'release'
    with:
      environment: "dev"
      logic_app_directory: "./code/logicApp001"
      logic_app_name: "mylogic-dev-la001"
    secrets:
      TENANT_ID: ${{ secrets.TENANT_ID }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
